name: Receive repository dispatch event

on:
    # Listen to a repository dispatch event by the name of `docs-repos-sync-with-template`
    repository_dispatch:
        types: [docs-repos-sync-with-template]

jobs:
    log:
        runs-on: ubuntu-latest
        steps:
            - name: Event received
              run: echo "Event received"
    test-implementation-job:
        runs-on: ubuntu-latest

        steps:
            # To use this repository's private action, you must check out the repository
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  # submodules: true
                  token: ${{ secrets.GH_PAT }}
            - name: Test action step PAT
              uses: AndreasAugustin/actions-template-sync@v2
              with:
                  github_token: ${{ secrets.GH_PAT }}
                  source_repo_path: anuragkanwar/main-template # <owner/repo>, should be within secrets

