name: Send repository dispatch event

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    trigger-event:
        runs-on: ubuntu-latest
        steps:
            - name: Fire event
              run: |
                  curl -L \
                    -X POST \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GH_PAT }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/anuragkanwar/main-template-prod/dispatches \
                    -d '{"event_type":"docs-repos-sync-with-template"}'
